version: '3.8'

services:
  tapis-api:
    image: tapis-api:1.0.0
    container_name: tapis_ap
    restart: always
    command: npm run start:dev
    build:
      context: .
      target: development
      dockerfile: dockerfile
    ports:
      - 4005:4005
    env_file:
      - .env
